name: gh-pages deploy pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.nvmrc'
      - '.github/workflows/*.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set node version with nvm
      shell: bash --login {0}
      run: nvm install

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      run: npm install

    - name: next lint
      run: npm run lint

    - name: Build
      run: npm run build --if-present

    - name: next export
      run: npm run export

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: out
