name: gh-pages deploy pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.nvmrc'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.nvmrc'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set node version with nvm
      shell: bash --login {0}
      run: nvm install

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      run: npm install

    - name: Build
      run: npm run build --if-present

    - name: Deploy to gh-pages
      run: |
        git config user.email hanqing.tan@gmail.com
        git config user.name hqtan
        git remote set-url origin https://"${github_token}"@github.com/${repository}
        scripts/ghpages-deploy.sh
      env:
        user_name: 'civic-makerbot'
        user_email: 'civic-makerbot@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
